name: Build YT Stream

on:
  push:
    branches: [ main, camera-feature  ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-obfuscate

      - name: Build AAB (Play Store)
        run: flutter build appbundle --release --no-obfuscate

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ytstream-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB (Play Store)
        uses: actions/upload-artifact@v4
        with:
          name: ytstream-aab-playstore
          path: build/app/outputs/bundle/release/app-release.aab
